language: node_js
# whitelist
branches:
  only:
    - src
node_js:
  - "5.7.1"
  # ruby: [How to run Node.js and Ruby tests within one project on Travis CI - Stack Overflow](http://stackoverflow.com/questions/31235146/how-to-run-node-js-and-ruby-tests-within-one-project-on-travis-ci/31373752#31373752)
before_install:
  - rvm install 2.3.1
script:
  # - ./build.sh
  - npm run jekyll
  - npm run postcss
  - npm run css-to-site
  - ./deploy-travis.sh
