language: node_js
# whitelist

# [The Travis CI Blog: Speed Up Your Builds: Cache Your Dependencies](https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies)
# workaround for which error: [RVM claims it can't find curl when using node-which · Issue #5092 · travis-ci/travis-ci](https://github.com/travis-ci/travis-ci/issues/5092#issuecomment-171936477)
# before_cache:
#   - rm ./node_modules/.bin/which
cache:
  bundler: true
  directories:
    - node_modules

branches:
  only:
    - src

node_js:
  - "5.7.1"
  # ruby: [How to run Node.js and Ruby tests within one project on Travis CI - Stack Overflow](http://stackoverflow.com/questions/31235146/how-to-run-node-js-and-ruby-tests-within-one-project-on-travis-ci/31373752#31373752)

before_install:
  # Dirty hack for https://github.com/travis-ci/travis-ci/issues/5092
  - >
    PATH=`echo $PATH | sed "s/\.\/node_modules\/\.bin//g"`;
    export PATH=$PATH:./node_modules/.bin;
  - rvm install 2.3.1
script:
  # - ./build.sh
  - npm run jekyll
  - npm run postcss
  - npm run css-to-site
  - ./deploy-travis.sh
