name: mono space
markdown: redcarpet
highlighter: true
permalink: :title/
baseurl:
url: http://filtercake.com


unpublished: true

exclude:
  - Procfile
  - render-linklist
  - render-tooling
  - Gemfile
  - Gemfile.lock
  - NOTES.md
  - Procfile
  - README.md
  - deploy.sh